### PR TITLE
feat: support for closed issues

### PR DESCRIPTION
**Pull request by Yash-Singh1**
I couldn't test this locally, so I'm not sure if it works without any bugs.

### CODE REVIEW

**Comment by oliverbutler** [comment]
👌

**Comment by shamwela** [comment]
To verify your on-demand ISR configuration is correct, you will need to create a [production build](https://nextjs.org/docs/api-reference/cli#build) and start the [production server](https://nextjs.org/docs/api-reference/cli#production).

**Comment by shamwela** [comment]
https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#testing-on-demand-isr-during-development

**Comment by leerob** [comment]
I'm only showing open issues for now 😄 Thank you though!

**Pull request closed without merging**
